services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
      - postgres
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: vhost
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_config worker --loglevel=info
    depends_on:
      - rabbitmq
      - fastapi

    stdin_open: true
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
